config/routes.rb
ParkmasterWeb::Application.routes.draw do
  
  resources :carts

  resources :payment_notifications

  resources :reservations

  resources :locations
  resources :locations do
    member do
      post 'reserve'
    end
  end

  get "sign_up" => "users#new", :as => "sign_up"  
  root :to => "pages#main"  
  resources :users
  resources :sessions

  
  get "help" => "pages#help", :as => "help"
  get "how_it_works" => "pages#how_it_works", :as => "how_it_works"
    

  get "log_in" => "sessions#new", :as => "log_in" 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "my_account" => "account#my_account", :as => "my_account"

    
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  validates :amount, :presence => true
  
  belongs_to :user
  attr_accessible :amount, :purchased_at
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(params[:cart])
    @cart.user = current_user
    
    if @cart.save
      session[:cart_id] ||= @cart.id
    end

    redirect_to my_account_url
  end

  def edit
    @cart = Cart.find(params[:id])
  end



  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil
    redirect_to my_account_url
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  
  def paypal_encrypted_request(return_url, notify_url)
    values = {
      :business => APP_CONFIG[:paypal_email],
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => @current_cart.id,
      :item_name_1 => "Parkey Credit",
      :quantity_1 => 1,
      :amount_1 => @current_cart.amount,
      :no_shipping => 2,
      :currency_code => "USD",
      :notify_url => notify_url,
      :cert_id => APP_CONFIG[:paypal_cert_id] 
    }
   
    encrypt_for_paypal(values)
  end
  
  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/" + APP_CONFIG[:paypal_cert_name])
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")
  
  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end
end

app/views/carts/_form.html.erb
<%= form_for @cart do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/carts/edit.html.erb
<% title "Edit Cart" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @cart %> |
  <%= link_to "View All", carts_path %>
</p>

app/views/carts/index.html.erb
<table>
  <tr>
    <th>Amount</th>
  </tr>
  <% for cart in @carts %>
    <tr>
      <td><%= cart.amount %></td>
      <td><%= link_to "Show", cart %></td>
      <td><%= link_to "Edit", edit_cart_path(cart) %></td>
      <td><%= link_to "Destroy", cart, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Cart", new_cart_path %></p>

app/views/carts/new.html.erb
<% title "New Cart" %>

<%= render 'form' %>

<p><%= link_to "Back to List", carts_path %></p>

app/views/carts/show.html.erb
<% title "Cart" %>

<p>
  <strong>Amount:</strong>
  <%= @cart.amount %>
</p>

<p>
  <%= link_to "Edit", edit_cart_path(@cart) %> |
  <%= link_to "Destroy", @cart, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", carts_path %>
</p>