config/routes.rb
ParkmasterWeb::Application.routes.draw do
  
  resources :carts

  resources :payment_notifications

  resources :reservations

  resources :locations
  resources :locations do
    member do
      post 'reserve'
    end
  end

  get "sign_up" => "users#new", :as => "sign_up"  
  root :to => "pages#main"  
  resources :users
  resources :sessions

  
  get "help" => "pages#help", :as => "help"
  get "how_it_works" => "pages#how_it_works", :as => "how_it_works"
    

  get "log_in" => "sessions#new", :as => "log_in" 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "my_account" => "account#my_account", :as => "my_account"

    
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :price, :opentime, :closetime 
  
  belongs_to :user
  belongs_to :reservation
  
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  
  def index
    @locations = Location.where("opentime > ?", Time.now).where(:reservation_id => nil)
    
    if @locations.length == 0 
       link = "<a href=\"#{url_for(new_location_path)}\">create one now</a>"    
       flash.now[:notice] = "No locations found. Why don't you #{link}?".html_safe
    end
  end

  def show
    @location = Location.find(params[:id])
  end
  
  def reserve
    location = Location.find(params[:id])
    location.reservation = Reservation.new(:user_id => current_user.id,:location_id => location.id)
    
    #make into transaction
    location.user.account.deposit(location.price)
    location.reservation.user.account.withdraw(location.price.to_d)
    
    location.user.account.save
    location.reservation.user.account.save
    
    UserMailer.reservation_confirmation(location.reservation.user, location).deliver
    UserMailer.reservation_notification(location.user, location).deliver
    
    if location.save
      redirect_to locations_path, :notice => "Successfully reserved location"
    else
      redirect_to location, :notice  => "Something bad happend making your reservation"
    end
    
  end

  def find
    
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])
    
    logger.debug "Here is the whole thing #{@location} and #{@location.closetime} #{@location.price} "
    
    @location.user = current_user
    
    UserMailer.location_confirmation(current_user, @location).deliver
    
    if @location.save
      redirect_to locations_path
    else
      render :action => 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      redirect_to @location, :notice  => "Successfully updated location"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_url
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>

  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  
<p>
    <%= f.label :price %> (in dollars)<br />
    <%= f.text_field :price %>
  </p>
<p>
    <%= f.label :opentime %><br />
    <%= f.text_field :opentime %>
  </p>
<p>
    <%= f.label :closetime %><br />
    <%= f.text_field :closetime %>
  </p>
  <p><%= f.submit "Create Parking Spot" , :class => "awesome" %></p>
<% end %>


<script>
	$(function() {
		$( "#location_opentime" ).datepicker({ dateFormat: "yy-mm-dd" });
		$( "#location_closetime" ).datepicker({ dateFormat: "yy-mm-dd" });
	});
	</script>

app/views/locations/edit.html.erb
<% title "Edit Spot" %>


<h1>Edit this Spot</h1>

<div class="section" style="width: 40%">

<%= render 'form' %>

<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

</div>

app/views/locations/index.html.erb
<% title "Open Spots" %>

<p id="notice"><span><%= notice %></span></p>

<table width="500">
  <tr>
	<th></th>
    <th>Address</th>
	<th>Date</th>
  </tr>

  <% @locations.each_with_index do  |location, index| %>
    <tr>
	  <td><%= index+1 %>.) 
      <td><%= location.address %></td>
	  <td><%= location.opentime.strftime("%m/%d/%Y") %></td>
      
		<% if location.user.id != current_user.id %>
			<td>
			<% if current_user.account.balance > location.price.to_d %>
				<%= link_to "Reserve", location %>
			<% else %>
					<span title="you lack the funds">Reserve</span>
			<% end %>
			
			</td>
		<% else %>
      		<td><%= link_to "Edit", edit_location_path(location) %></td>
      		<td><%= link_to "Remove", location, :method => :delete %></td>
		<% end %>
    </tr>
  <% end %>
</table>

<div id="map_canvas" style="width:60%; height:400px; margin: 10px; float:left"></div>

<div class="toggler" style="width:30%;float:left" >
	<div id="effect" >
		
		
		<h2>Parking Spot</h2>
		<div class="section">
		<div>
			<span>(picture)</span>
			<span> </span>
		</div>
		
		<div>
			<span class="pLabel">Price: $</span>
			<span id="spot_price"> </span>
		</div>
			
		<div>
			<span class="pLabel">Date: </span>
			<span id="spot_date"> </span>
		</div>
			
		<div>
			<span class="pLabel">Owner: </span>
			<span id="spot_owner"> </span>
		</div>
		
		<div>
			<span class="pLabel">Notes: </span>
			<span id="spot_notes"> Blah blah blah blah blah Blah blah blah blah blah</span>
		</div>
			
		<div>
			<input type="button" class="awesome" id="spot_button" value="Reserve"></a>
		</div>	
		</div>	
	</div>
</div>

<div style="clear:both">
<p><%= link_to "New Parking Spot", new_location_path %> | <%= link_to "Home", root_path %> </p>
</div>



<script type="text/javascript">
	
	$(function() {
      
		var mapOptions = {
          //hard code boulder for now
         center: new google.maps.LatLng(40.0149856, -105.27054560),
          zoom: 15,
		  draggable: false,
		 disableDoubleClickZoom: true,
		scrollwheel: false,
		  disableDefaultUI: true,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),
            mapOptions);

		<% @locations.each_with_index do  |location, index| %>
				var latlng<%= location.id %> = new google.maps.LatLng(<%= location.latitude %>,<%= location.longitude %>);
	   
				var marker<%= location.id %> = new google.maps.Marker({
								            position: latlng<%= location.id %>,
								            map: map,
											title:"Price: $<%= location.price %>",
											icon: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld='+<%=index+1%>+'|FA6173|000000'
								
								        });
								
				google.maps.event.addListener(marker<%= location.id %>, 'click', function() {
										    runEffect('<%= location.price %>','<%= location.opentime %>','<%= location.user.email %>', '<%= location.id %>');
				});
	   <% end %>
	
		
		
		// run the currently selected effect
				function runEffect(location_price, location_date, location_owner, location_id) {
					// most effect types need no options passed by default
					var options = {};
				 $('#spot_price').text(location_price);
				 $('#spot_date').text(location_date);
				 $('#spot_owner').text(location_owner);
				 $('#spot_button').click(function() { alert('foo'); });
					
					// run the effect
					$( "#effect" ).show( "blind", options, 500, callback );
				};

				//callback function to bring a hidden box back
				function callback() {
				//	setTimeout(function() {
				//		$( "#effect:visible" ).removeAttr( "style" ).fadeOut();
				//	}, 1000 );
				};

				// set effect from select menu value
				$( "#button" ).click(function() {
					runEffect();
					return false;
				});

			$( "#effect" ).hide();
		
      });


    </script>

app/views/locations/new.html.erb
<% title "Add a new Spot" %>

<h1>Add a new Parking Spot</h1>

<div class="section" style="width: 40%">
<%= render 'form' %>

</div>

<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/reserve.html.erb
<h1>Reserve this spot</h1>

<div class="section">
<%= @location.address %>

</div>

app/views/locations/show.html.erb
<% title "Reserve This Spot" %>

<h1>Reserve this spot</h1>

<div class="section" style="width: 40%">
<table>
	<tr>
		<td>Address:</td>
		<td><%= @location.address %></td>
	</tr>
	<tr>
		<td>Price:</td>
		<td>$<%= @location.price %></td>
	</tr>
	<tr>
		<td>Owner:</td>
		<td><a href="mailto:<%= @location.user.email %>"><%= @location.user.email %></a></td>
	</tr>
</table>


<div style="margin-top: 50px">
<%= button_to "Reserve this Spot", {:controller => 'locations', :action => "reserve" }, {:class => "awesome"} %>
</div>

</div>