config/routes.rb
ParkmasterWeb::Application.routes.draw do
  
  resources :carts

  resources :payment_notifications

  resources :reservations

  resources :locations
  resources :locations do
    member do
      post 'reserve'
    end
  end

  get "sign_up" => "users#new", :as => "sign_up"  
  root :to => "pages#main"  
  resources :users
  resources :sessions

  
  get "help" => "pages#help", :as => "help"
  get "how_it_works" => "pages#how_it_works", :as => "how_it_works"
    

  get "log_in" => "sessions#new", :as => "log_in" 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "my_account" => "account#my_account", :as => "my_account"

    
  
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js"> 
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <meta name="description" content="">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">
	
    <%= stylesheet_link_tag    "application", :media => "all" %>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" type="text/css" media="all" />
  	<%= javascript_include_tag "application" %>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyD9sZajBqv25DwxzxNJHmdB-aqWJ4c5AOE&sensor=false"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.js"></script>


  	<%= csrf_meta_tags %>
</head>
<body>
	<div class="site-header" id="dark-header">
	<div id="inner-header" class="center">

	   	<div id="current-user" class="right"> 
			<% if current_user %>  
		    Logged in as <%= current_user.email %>  | <%= link_to "My Account", my_account_path %>  |
		    <%= link_to "Log out", log_out_path %>  
		  <% end %>
		</div>
	    <div class="clear-float"></div>
	  </div>
	</div>
	
	
	<div >

		<div>
			<%= yield %>
		</div>
	</div>
	


</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html class="no-js"> 
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    ￼<title></title>
    <meta name="description" content="">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">
	
    <%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
	
  	<%= csrf_meta_tags %>

</head>
<body>

	<div class="container">
			<p id="alert"><span style="color:red"><%= alert %></span></p>
		<div>
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html class="no-js"> 
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title></title>
    <meta name="description" content="">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">
	
    <%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
</head>
<body>
	
	<div class="container">
		<div id="user_nav"  align="right">  
		  <% if current_user %>  
		    Logged in as <%= current_user.email %>  
		    <%= link_to "Log out", log_out_path %>  
		  <% else %>   
		    <%= link_to "Log in", log_in_path %>  
		  <% end %>  
		</div>
		<div>
			<%= yield %>
		</div>
	</div>

</body>
</html>